/* eslint-disable import/export */
import { icons } from '../utils';

export const Links: Data[] = [
  {
    id: 0,
    name: 'Github',
    link: 'https://github.com/WomB0ComB0',
    type: 'Development',
    sourceSVG: icons.development.GithubIcon,
    description: '',
    featured: true,
  },
  {
    id: 1,
    name: 'Gitlab',
    link: 'https://gitlab.com/WomB0ComB0',
    type: 'Development',
    sourceSVG: icons.development.GitLabIcon,
    description: '',
    featured: false,
  },
  {
    id: 2,
    name: 'Instagram',
    link: 'https://www.instagram.com/_xmike__/',
    type: 'Socials',
    sourceSVG: icons.socials.InstagramIcon,
    description: '',
    featured: false,
  },
  {
    id: 3,
    name: 'Twitter',
    link: 'https://twitter.com/OdnisMike',
    type: 'Socials',
    sourceSVG: icons.socials.TwitterIcon,
    description: '',
    featured: false,
  },
  {
    id: 4,
    name: 'Discord',
    link: 'https://discordapp.com/users/194258098402230272',
    type: 'Socials',
    sourceSVG: icons.socials.DiscordIcon,
    description: '',
    featured: false,
  },
  {
    id: 5,
    name: 'DevTo',
    link: 'https://dev.to/womb0comb0',
    type: 'Socials',
    sourceSVG: icons.socials.DevToIcon,
    description: '',
    featured: false,
  },
  {
    id: 6,
    name: 'Medium',
    link: 'https://medium.com/@mikeodnis3242004',
    type: 'Socials',
    sourceSVG: icons.socials.MediumIcon,
    description: '',
    featured: false,
  },
  {
    id: 7,
    name: 'LinkedIn',
    link: 'https://linkedin.com/in/mikeodnis',
    type: 'Networking',
    sourceSVG: icons.networking.LinkedInIcon,
    description: '',
    featured: false,
  },
  {
    id: 8,
    name: 'CodersRank',
    link: 'https://profile.codersrank.io/user/womb0comb0',
    type: 'Networking',
    sourceSVG: icons.networking.CodersRankIcon,
    description: '',
    featured: false,
  },
  {
    id: 9,
    name: 'Dribble',
    link: 'https://dribbble.com/WomB0ComB0',
    type: 'Design',
    sourceSVG: icons.design.DribbleIcon,
    description: '',
    featured: false,
  },
  {
    id: 10,
    name: 'Codepen',
    link: 'https://codepen.io/womb0comb0',
    type: 'Design',
    sourceSVG: icons.design.CodePenIcon,
    description: '',
    featured: false,
  },
  {
    id: 11,
    name: 'Leetcode',
    link: 'https://leetcode.com/WomB0ComB0/',
    type: 'Learning',
    sourceSVG: icons.learning.LeetCodeIcon,
    description: '',
    featured: false,
  },
  {
    id: 12,
    name: 'HackerRank',
    link: 'https://www.hackerrank.com/airwolf635',
    type: 'Learning',
    sourceSVG: icons.learning.HackerRankIcon,
    description: '',
    featured: false,
  },
  {
    id: 13,
    name: 'Microsoft Learning',
    link: 'https://learn.microsoft.com/en-us/users/mikeodnis/',
    type: 'Learning',
    sourceSVG: icons.learning.MicrosoftLearnIcon,
    description: '',
    featured: false,
  },
  {
    id: 14,
    name: 'SoloLearn',
    link: 'https://www.sololearn.com/profile/24459722',
    type: 'Learning',
    sourceSVG: icons.learning.SoloLearnIcon,
    description: '',
    featured: false,
  },
  {
    id: 15,
    name: 'FreeCodeCamp',
    link: 'https://www.freecodecamp.org/WomB0ComB0',
    type: 'Learning',
    sourceSVG: icons.learning.FCCIcon,
    description: '',
    featured: false,
  },
];

export const NavLinks: Links[] = [
  {
    name: 'Portfolio',
    link: 'https://www.mikeodnis.com',
  },
  {
    name: 'Stats',
    link: 'https://womb0comb0.github.io/mikeodnis-page/',
  },
  {
    name: 'Resume',
    link: 'https://docs.google.com/document/d/1ItV1Ugn87fBE8RvKji7_a5pZ8zbA59eZGVojnCoGiQA/edit?usp=sharing',
  },
];
